package edu.uco.jdrumm.projectkye.Level;

import edu.uco.jdrumm.projectkye.Game.BaseObject;
import edu.uco.jdrumm.projectkye.Game.BlackHole;
import edu.uco.jdrumm.projectkye.Game.BlockCircle;
import edu.uco.jdrumm.projectkye.Game.Diamond;
import edu.uco.jdrumm.projectkye.Game.ForceField;
import edu.uco.jdrumm.projectkye.Game.FuzzBlock;
import edu.uco.jdrumm.projectkye.Game.Kye;
import edu.uco.jdrumm.projectkye.Game.Monster;
import edu.uco.jdrumm.projectkye.Game.Rotator;
import edu.uco.jdrumm.projectkye.Game.RoundSlider;
import edu.uco.jdrumm.projectkye.Game.Sentry;
import edu.uco.jdrumm.projectkye.Game.TimeBlock;
import edu.uco.jdrumm.projectkye.Game.VerticalMagnet;
import edu.uco.jdrumm.projectkye.Game.Wall;
import edu.uco.jdrumm.projectkye.Orientation.Direction;
import edu.uco.jdrumm.projectkye.Orientation.Rotation;
import edu.uco.jdrumm.projectkye.R;

public class Level15 extends Level
{
    public Level15()
    {
        super();
        levelName = "RockyV";
    }

    @Override
    protected void createObjects()
    {
        objects = new BaseObject[]{
                new Rotator(1, 1, Rotation.COUNTER_CLOCKWISE),
                new TimeBlock(11, 1, 9),
                new RoundSlider(12, 1, Direction.LEFT),
                new RoundSlider(13, 1, Direction.LEFT),
                new RoundSlider(14, 1, Direction.LEFT),
                new RoundSlider(15, 1, Direction.LEFT),
                new RoundSlider(16, 1, Direction.LEFT),
                new RoundSlider(17, 1, Direction.LEFT),
                new RoundSlider(18, 1, Direction.LEFT),
                new RoundSlider(19, 1, Direction.LEFT),
                new RoundSlider(20, 1, Direction.LEFT),
                new RoundSlider(21, 1, Direction.LEFT),
                new RoundSlider(22, 1, Direction.LEFT),
                new RoundSlider(23, 1, Direction.LEFT),
                new RoundSlider(24, 1, Direction.LEFT),
                new Rotator(25, 1, Rotation.COUNTER_CLOCKWISE),
                new Wall(26, 1, 1),
                new Wall(27, 1),
                //new Diamond(28, 1),

                new Wall(3, 2, 4),
                new Wall(4, 2),
                new Wall(5, 2),
                new Wall(6, 2),
                new Wall(7, 2),
                new Wall(8, 2),
                new Wall(9, 2, 9),
                new TimeBlock(12, 2, 9),
                new RoundSlider(13, 2, Direction.LEFT),
                new RoundSlider(14, 2, Direction.LEFT),
                new RoundSlider(15, 2, Direction.LEFT),
                new RoundSlider(16, 2, Direction.LEFT),
                new Wall(17, 2, 7),
                new Rotator(18, 2, Rotation.CLOCKWISE),
                new Wall(19, 2),
                new Wall(20, 2),
                new Wall(21, 2),
                new Wall(22, 2),
                new Wall(23, 2, 9),
                new RoundSlider(24, 2, Direction.LEFT),
                new RoundSlider(25, 2, Direction.UP),
                new Rotator(26, 2, Rotation.CLOCKWISE),
                new Wall(27, 2),

                new RoundSlider(2, 3, Direction.DOWN),
                new Wall(4, 3),
                new FuzzBlock(5, 3),
                new FuzzBlock(6, 3),
                new BlackHole(7, 3),
                new Wall(9, 3, 1),
                new Wall(10, 3),
                new Wall(11, 3, 6),
                new ForceField(12, 3, Direction.DOWN),
                new Wall(13, 3, 7),
                new Wall(14, 3),
                new Wall(15, 3),
                new Wall(16, 3),
                new Wall(17, 3),
                new RoundSlider(18, 3, Direction.UP),
                new FuzzBlock(19, 3),
                new RoundSlider(20, 3, Direction.RIGHT),
                new FuzzBlock(21, 3),
                new RoundSlider(22, 3, Direction.DOWN),
                new Wall(23, 3, 2),
                new RoundSlider(24, 3, Direction.DOWN),
                new RoundSlider(25, 3, Direction.UP),
                new Rotator(26, 3, Rotation.CLOCKWISE),
                new Wall(27, 3),

                new RoundSlider(1, 4, Direction.DOWN),
                new RoundSlider(2, 4, Direction.DOWN),
                new RoundSlider(3, 4, Direction.DOWN),
                new Wall(4, 4, 2),
                new Kye(5, 4),
                new BlockCircle(6, 4),
                new BlackHole(7, 4),
                new Diamond(8, 4),
                new RoundSlider(9, 4, Direction.DOWN),
                new Diamond(11, 4),
                new Wall(13, 4),
                new Diamond(15, 4),
                new RoundSlider(16, 4, Direction.DOWN),
                new Wall(17, 4),
                new FuzzBlock(18, 4),
                new Wall(19, 4, 8),
                new Diamond(20, 4),
                new RoundSlider(21, 4, Direction.RIGHT),
                new FuzzBlock(22, 4),
                new RoundSlider(23, 4, Direction.RIGHT),
                new FuzzBlock(24, 4),
                new RoundSlider(25, 4, Direction.UP),
                new Rotator(26, 4, Rotation.CLOCKWISE),
                new Wall(27, 4),

                new RoundSlider(1, 5, Direction.DOWN),
                new RoundSlider(2, 5, Direction.DOWN),
                new RoundSlider(3, 5, Direction.DOWN),
                new RoundSlider(4, 5, Direction.RIGHT),
                new TimeBlock(5, 5, 3),
                new FuzzBlock(7, 5),
                new FuzzBlock(8, 5),
                new TimeBlock(11, 5, 3),
                new Wall(13, 5),
                new RoundSlider(14, 5, Direction.DOWN),
                new FuzzBlock(15, 5),
                new Sentry(16, 5, Direction.LEFT),
                new Wall(17, 5),
                new RoundSlider(18, 5, Direction.UP),
                new Wall(19, 5),
                new Monster(20, 5, Monster.Monsters.BLOB),
                new BlackHole(21, 5),
                new RoundSlider(22, 5, Direction.RIGHT),
                new FuzzBlock(23, 5),
                new RoundSlider(24, 5, Direction.DOWN),
                new RoundSlider(25, 5, Direction.UP),
                new Rotator(26, 5, Rotation.CLOCKWISE),
                new Wall(27, 5),

                new Rotator(1, 6, Rotation.COUNTER_CLOCKWISE),
                new Rotator(2, 6, Rotation.COUNTER_CLOCKWISE),
                new Rotator(3, 6, Rotation.COUNTER_CLOCKWISE),
                new Wall(4, 6),
                new Wall(5, 6, 9),
                new RoundSlider(8, 6, Direction.UP),
                new VerticalMagnet(9, 6),
                new RoundSlider(10, 6, Direction.UP),
                new RoundSlider(11, 6, Direction.UP),
                new Wall(13, 6),
                new Diamond(14, 6),
                new FuzzBlock(15, 6),
                new Wall(17, 6),
                new Wall(19, 6),
                new Diamond(20, 6),
                new Wall(21, 6),
                new Rotator(22, 6, Rotation.COUNTER_CLOCKWISE),
                new RoundSlider(23, 6, Direction.RIGHT),
                new FuzzBlock(24, 6),
                new RoundSlider(25, 6, Direction.UP),
                new Rotator(26, 6, Rotation.CLOCKWISE),
                new Wall(27, 6),

                new Wall(1, 7),
                new Wall(2, 7),
                new Wall(3, 7),
                new Wall(4, 7),
                new Wall(5, 7),
                new Wall(6, 7),
                new Wall(7, 7),
                new Wall(8, 7),
                new Wall(9, 7),
                new Wall(10, 7),
                new Wall(11, 7),
                new Wall(12, 7),
                new Wall(13, 7),
                new Wall(14, 7, 9),
                new Wall(16, 7, 7),
                new Wall(17, 7),
                new Wall(18, 7),
                new Wall(19, 7),
                new Wall(20, 7),
                new Wall(21, 7),
                new Wall(22, 7),
                new Wall(23, 7),
                new Wall(24, 7, 9),
                new RoundSlider(25, 7, Direction.UP),
                new Wall(26, 7, 4),
                new Wall(27, 7, 3),

                new Monster(1, 8, Monster.Monsters.BLOB),
                new Wall(4, 8),
                new BlackHole(6, 8),
                new BlockCircle(9, 8),
                new Diamond(10, 8),
                new BlockCircle(11, 8),
                new Wall(13, 8, 1),
                new Wall(14, 8, 3),
                new Wall(16, 8, 1),
                new Wall(19, 8, 1),
                new Wall(20, 8, 3),
                new Diamond(22, 8),
                new Wall(23, 8),
                new Wall(24, 8),
                new RoundSlider(25, 8, Direction.UP),

                new Wall(4, 9),
                new ForceField(6, 9, Direction.LEFT),
                new BlockCircle(8, 9),
                new BlockCircle(10, 9),
                new ForceField(13, 9, Direction.LEFT),
                new ForceField(16, 9, Direction.LEFT),
                new RoundSlider(19, 9, Direction.LEFT),
                new Diamond(20, 9),
                new Diamond(22, 9),
                new Wall(23, 9),
                new Wall(24, 9),
                new Rotator(28, 9, Rotation.COUNTER_CLOCKWISE),

                new Wall(1, 10),
                new Wall(2, 10, 9),
                new Wall(4, 10),
                new BlackHole(6, 10),
                new BlockCircle(7, 10),
                new BlockCircle(11, 10),
                new Wall(13, 10, 7),
                new Wall(14, 10, 9),
                new Wall(16, 10, 7),
                new RoundSlider(17, 10, Direction.RIGHT),
                new Diamond(18, 10),
                new Wall(21, 10, 8),
                new Diamond(22, 10),
                new Wall(23, 10),
                new Wall(24, 10),
                new Rotator(25, 10, Rotation.COUNTER_CLOCKWISE),
                new Wall(27, 10, 7),
                new Wall(28, 10),

                new Wall(1, 11),
                new Wall(2, 11),
                new Wall(4, 11),
                new Wall(6, 11, 7),
                new Wall(7, 11),
                new Wall(8, 11),
                new Wall(9, 11),
                new Wall(10, 11),
                new Wall(11, 11),
                new Wall(12, 11),
                new Wall(13, 11),
                new Wall(14, 11, 3),
                new Wall(16, 11, 1),
                new Wall(17, 11),
                new Wall(18, 11),
                new Wall(19, 11),
                new Wall(20, 11),
                new Wall(21, 11),
                new Wall(22, 11),
                new Wall(23, 11),
                new Wall(24, 11),
                new Wall(25, 11, 6),
                new Wall(27, 11, 7),
                new Wall(28, 11),

                new Wall(1, 12),
                new Wall(2, 12),
                new Wall(4, 12),
                new Wall(6, 12),
                new Wall(7, 12, 3),
                new Diamond(9, 12),
                new FuzzBlock(10, 12),
                new FuzzBlock(11, 12),
                new Rotator(12, 12, Rotation.COUNTER_CLOCKWISE),
                new Wall(13, 12),
                new FuzzBlock(15, 12),
                new Diamond(16, 12),
                new Wall(17, 12),
                new Wall(18, 12),
                new Wall(19, 12),
                new Wall(20, 12, 3),
                new Rotator(21, 12, Rotation.COUNTER_CLOCKWISE),
                new Wall(22, 12),
                new Wall(23, 12),
                new Wall(24, 12, 3),
                new Wall(27, 12, 3),
                new RoundSlider(28, 12, Direction.LEFT),

                new Wall(1, 13),
                new Wall(2, 13, 3),
                new Wall(4, 13),
                new Wall(6, 13),
                new Diamond(9, 13),
                new FuzzBlock(10, 13),
                new FuzzBlock(11, 13),
                new Wall(13, 13),
                new Sentry(14, 13, Direction.RIGHT),
                new FuzzBlock(15, 13),
                new RoundSlider(16, 13, Direction.UP),
                new Wall(17, 13),
                new Rotator(18, 13, Rotation.COUNTER_CLOCKWISE),
                new Wall(22, 13),
                new Wall(23, 13, 3),
                new Wall(26, 13, 3),
                new RoundSlider(27, 13, Direction.LEFT),
                new RoundSlider(28, 13, Direction.LEFT),

                new Wall(1, 14),
                new Wall(4, 14),
                new FuzzBlock(5, 14),
                new Wall(6, 14),
                new Wall(8, 14, 4),
                new Wall(9, 14),
                new Wall(10, 14),
                new Wall(11, 14, 6),
                new Wall(13, 14),
                new RoundSlider(14, 14, Direction.UP),
                new Diamond(15, 14),
                new Wall(17, 14),
                new Wall(20, 14, 8),
                new Wall(22, 14),
                new Rotator(23, 14, Rotation.COUNTER_CLOCKWISE),
                new Wall(25, 14, 2),
                new RoundSlider(26, 14, Direction.LEFT),
                new RoundSlider(27, 14, Direction.LEFT),
                new RoundSlider(28, 14, Direction.LEFT),

                new Wall(1, 15, 3),
                new Wall(3, 15, 4),
                new Wall(4, 15, 3),
                new Rotator(8, 15, Rotation.COUNTER_CLOCKWISE),
                new Wall(9, 15, 1),
                new Wall(10, 15),
                new Rotator(11, 15, Rotation.CLOCKWISE),
                new Wall(13, 15),
                new Wall(14, 15),
                new Wall(15, 15),
                new Wall(16, 15),
                new Wall(17, 15),
                new Wall(20, 15),
                new Wall(22, 15),
                new Rotator(23, 15, Rotation.COUNTER_CLOCKWISE),
                new Diamond(24, 15),
                new RoundSlider(25, 15, Direction.LEFT),
                new RoundSlider(26, 15, Direction.LEFT),
                new RoundSlider(27, 15, Direction.LEFT),
                new RoundSlider(28, 15, Direction.LEFT),

                new Rotator(1, 16, Rotation.CLOCKWISE),
                new RoundSlider(6, 16, Direction.DOWN),
                new Rotator(9, 16, Rotation.COUNTER_CLOCKWISE),
                new Wall(10, 16),
                new Rotator(11, 16, Rotation.CLOCKWISE),
                new Wall(13, 16, 1),
                new Wall(14, 16),
                new Wall(15, 16),
                new Wall(16, 16),
                new Wall(17, 16, 3),
                new Wall(19, 16, 7),
                new Wall(20, 16, 3),
                new Wall(22, 16, 2),
                new Rotator(23, 16, Rotation.COUNTER_CLOCKWISE),
                new Wall(25, 16, 8),
                new RoundSlider(26, 16, Direction.LEFT),
                new RoundSlider(27, 16, Direction.LEFT),
                new RoundSlider(28, 16, Direction.LEFT),

                new Wall(1, 17, 9),
                new FuzzBlock(6, 17),
                new Rotator(9, 17, Rotation.COUNTER_CLOCKWISE),
                new Wall(10, 17),
                new Rotator(11, 17, Rotation.CLOCKWISE),
                new Wall(19, 17),
                new Rotator(20, 17, Rotation.CLOCKWISE),
                new Wall(25, 17),
                new Wall(26, 17, 9),
                new RoundSlider(27, 17, Direction.LEFT),
                new RoundSlider(28, 17, Direction.LEFT),

                new Wall(1, 18),
                new Wall(2, 18),
                new Wall(3, 18),
                new Wall(4, 18, 9),
                new Rotator(5, 18, Rotation.COUNTER_CLOCKWISE),
                new Rotator(6, 18, Rotation.COUNTER_CLOCKWISE),
                new Wall(7, 18, 7),
                new Wall(8, 18, 9),
                new Rotator(9, 18, Rotation.COUNTER_CLOCKWISE),
                new Wall(10, 18),
                new Rotator(11, 18, Rotation.CLOCKWISE),
                new Wall(17, 18, 8),
                new Rotator(18, 18, Rotation.CLOCKWISE),
                new Wall(19, 18),
                new Wall(20, 18),
                new Wall(21, 18),
                new Wall(22, 18),
                new Wall(23, 18, 9),
                new Rotator(25, 18, Rotation.CLOCKWISE),
                new Wall(25, 18),
                new Wall(26, 18),
                new Wall(27, 18),
                new RoundSlider(28, 18, Direction.LEFT)
        };
    }
}
