package edu.uco.jdrumm.projectkye.Level;

import edu.uco.jdrumm.projectkye.Game.BaseObject;
import edu.uco.jdrumm.projectkye.Game.Block;
import edu.uco.jdrumm.projectkye.Game.Diamond;
import edu.uco.jdrumm.projectkye.Game.FuzzBlock;
import edu.uco.jdrumm.projectkye.Game.HorizontalMagnet;
import edu.uco.jdrumm.projectkye.Game.Kye;
import edu.uco.jdrumm.projectkye.Game.Monster;
import edu.uco.jdrumm.projectkye.Game.RoundSlider;
import edu.uco.jdrumm.projectkye.Game.Sentry;
import edu.uco.jdrumm.projectkye.Game.SquareSlider;
import edu.uco.jdrumm.projectkye.Game.VerticalMagnet;
import edu.uco.jdrumm.projectkye.Game.Wall;
import edu.uco.jdrumm.projectkye.Orientation.Direction;

public class Level8 extends Level
{
    public Level8()
    {
        super();
        levelMessage = "Ho hum, now for some work";
        levelName = "Circus";
    }

    @Override
    protected void createObjects()
    {
        objects = new BaseObject[]{
                new Wall(2, 1),
                new Diamond(3, 1),
                new Wall(4, 1),
                new Wall(5, 1),
                new Wall(6, 1),
                new FuzzBlock(7, 1),
                new FuzzBlock(8, 1),
                new SquareSlider(9, 1, Direction.DOWN),
                new Wall(16, 1),
                new Wall(21, 1),

                new Wall(2, 2),
                new RoundSlider(3, 2, Direction.DOWN),
                new Wall(4, 2),
                new HorizontalMagnet(5, 2),
                new FuzzBlock(6, 2),
                new FuzzBlock(7, 2),
                new SquareSlider(8, 2, Direction.UP),
                new SquareSlider(9, 2, Direction.DOWN),
                new Wall(16, 2),
                new RoundSlider(17, 2, Direction.DOWN),
                new RoundSlider(18, 2, Direction.DOWN),
                new RoundSlider(19, 2, Direction.DOWN),
                new RoundSlider(20, 2, Direction.DOWN),
                new Wall(21, 2),
                new SquareSlider(24, 2, Direction.RIGHT),
                new SquareSlider(25, 2, Direction.DOWN),
                new SquareSlider(26, 2, Direction.DOWN),

                new RoundSlider(1, 3, Direction.DOWN),
                new Wall(2, 3),
                new RoundSlider(3, 3, Direction.DOWN),
                new Wall(4, 3),
                new Block(5, 3),
                new Block(6, 3),
                new Block(7, 3),
                new SquareSlider(8, 3, Direction.UP),
                new FuzzBlock(9, 3),
                new Wall(16, 3),
                new RoundSlider(17, 3, Direction.DOWN),
                new RoundSlider(18, 3, Direction.DOWN),
                new RoundSlider(19, 3, Direction.DOWN),
                new RoundSlider(20, 3, Direction.DOWN),
                new Wall(21, 3),
                new SquareSlider(24, 3, Direction.RIGHT),
                new Diamond(25, 3),
                new SquareSlider(26, 3, Direction.LEFT),

                new RoundSlider(1, 4, Direction.DOWN),
                new Wall(2, 4, 2),
                new FuzzBlock(3, 4),
                new Wall(4, 4),
                new FuzzBlock(17, 4),
                new FuzzBlock(18, 4),
                new FuzzBlock(19, 4),
                new FuzzBlock(20, 4),
                new Block(21, 4),
                new SquareSlider(24, 4, Direction.UP),
                new SquareSlider(25, 4, Direction.UP),
                new SquareSlider(26, 4, Direction.LEFT),

                new FuzzBlock(1, 5),
                new FuzzBlock(2, 5),
                new Wall(4, 5),
                new Wall(17, 5, 7),
                new Wall(18, 5),
                new Wall(19, 5),
                new Wall(20, 5),
                new Wall(21, 5),
                new Wall(22, 5),
                new Wall(23, 5),
                new Wall(24, 5),
                new Wall(25, 5),
                new Wall(26, 5),
                new Wall(27, 5),
                new Wall(28, 5),

                new Wall(4, 6, 1),
                new Wall(5, 6),
                new Wall(6, 6),
                new Wall(7, 6),
                new Wall(8, 6),
                new Wall(9, 6),
                new Wall(10, 6),
                new Wall(11, 6),
                new Wall(12, 6),
                new Wall(13, 6),
                new Wall(14, 6),
                new Wall(15, 6, 9),
                new Wall(25, 6),

                new RoundSlider(7, 7, Direction.UP),
                new Sentry(14, 7, Direction.LEFT),
                new Wall(15, 7),
                new Kye(20, 7),
                new Wall(25, 7),

                new Wall(1, 8),
                new Wall(2, 8),
                new Wall(3, 8, 9),
                new Wall(8, 8, 7),
                new Wall(9, 8),
                new Wall(10, 8),
                new Wall(11, 8),
                new Wall(12, 8, 9),
                new RoundSlider(14, 8, Direction.DOWN),
                new Wall(15, 8, 1),
                new Wall(16, 8),
                new Wall(17, 8),
                new Wall(18, 8, 9),
                new Block(25, 8),

                new Wall(2, 9),
                new Wall(3, 9),
                new Wall(4, 9),
                new Wall(5, 9),
                new Wall(6, 9),
                new Wall(7, 9),
                new Wall(8, 9),
                new Wall(9, 9),
                new Wall(10, 9),
                new Wall(11, 9),
                new Wall(12, 9),
                new FuzzBlock(13, 9),
                new FuzzBlock(14, 9),
                new Wall(18, 9),
                new Wall(19, 9, 9),
                new Block(25, 9),
                new Monster(27, 9, Monster.Monsters.BLOB),

                new Wall(12, 10),
                new Wall(13, 10, 9),
                new FuzzBlock(14, 10),
                new FuzzBlock(18, 10),
                new Wall(19, 10),
                new Sentry(20, 10, Direction.DOWN),
                new Block(25, 10),

                new Wall(13, 11),
                new Wall(14, 11),
                new Wall(15, 11, 6),
                new Wall(17, 11, 4),
                new Wall(18, 11),
                new Wall(19, 11),
                new Wall(25, 11, 3),

                new Wall(5, 12, 4),
                new Wall(6, 12),
                new FuzzBlock(7, 12),
                new Wall(8, 12, 9),
                new Wall(25, 12),
                new Diamond(28, 12),

                new Wall(3, 13, 8),
                new FuzzBlock(5, 13),
                new RoundSlider(6, 13, Direction.RIGHT),
                new RoundSlider(7, 13, Direction.UP),
                new Wall(8, 13, 1),
                new Wall(9, 13),
                new Wall(10, 13),
                new Wall(14, 13),
                new Wall(15, 13),
                new Wall(16, 13),
                new Wall(17, 13),
                new Wall(18, 13),
                new Wall(21, 13, 7),
                new Wall(22, 13),
                new Wall(23, 13),
                new Wall(24, 13),
                new Wall(25, 13),
                new Wall(26, 13),
                new Wall(27, 13),
                new Wall(28, 13),

                new Wall(3, 14),
                new FuzzBlock(6, 14),
                new RoundSlider(7, 14, Direction.LEFT),
                new Diamond(9, 14),
                new Wall(10, 14),
                new Wall(14, 14),
                new SquareSlider(15, 14, Direction.DOWN),
                new FuzzBlock(16, 14),
                new Diamond(17, 14),
                new Wall(18, 14),
                new FuzzBlock(23, 14),
                new RoundSlider(24, 14, Direction.DOWN),
                new FuzzBlock(25, 14),
                new RoundSlider(26, 14, Direction.DOWN),
                new FuzzBlock(27, 14),
                new RoundSlider(28, 14, Direction.DOWN),

                new Wall(3, 15, 1),
                new Wall(4, 15),
                new Wall(5, 15),
                new Wall(6, 15),
                new Wall(7, 15),
                new Wall(8, 15),
                new Wall(9, 15),
                new Wall(10, 15),
                new FuzzBlock(14, 15),
                new FuzzBlock(15, 15),
                new Wall(16, 15),
                new Wall(17, 15),
                new Wall(18, 15),
                new Wall(21, 15),
                new RoundSlider(22, 15, Direction.RIGHT),
                new FuzzBlock(23, 15),
                new FuzzBlock(24, 15),
                new FuzzBlock(25, 15),
                new FuzzBlock(26, 15),
                new FuzzBlock(27, 15),
                new RoundSlider(28, 15, Direction.LEFT),

                new Wall(10, 16),
                new Wall(21, 16),
                new FuzzBlock(22, 16),
                new RoundSlider(23, 16, Direction.UP),
                new RoundSlider(25, 16, Direction.UP),
                new FuzzBlock(26, 16),
                new RoundSlider(27, 16, Direction.UP),
                new FuzzBlock(28, 16),

                new Wall(1, 17),
                new Block(2, 17),
                new Block(3, 17),
                new Wall(4, 17),
                new Wall(5, 17),
                new Wall(8, 17),
                new Wall(9, 17),
                new Wall(10, 17),
                new VerticalMagnet(11, 17),
                new Wall(12, 17),
                new Wall(13, 17),
                new Wall(14, 17),
                new Wall(15, 17),
                new Wall(16, 17),
                new Wall(17, 17),
                new FuzzBlock(18, 17),
                new FuzzBlock(19, 17),
                new FuzzBlock(20, 17),
                new Wall(21, 17),
                new Wall(22, 17),
                new Wall(23, 17),
                new Wall(24, 17),
                new Wall(25, 17),
                new Wall(26, 17),
                new Wall(27, 17),

                new Diamond(1, 18),
                new SquareSlider(11, 18, Direction.LEFT),
                new SquareSlider(12, 18, Direction.LEFT),
                new SquareSlider(13, 18, Direction.LEFT),
                new SquareSlider(14, 18, Direction.LEFT),
                new RoundSlider(27, 18, Direction.RIGHT),
                new Diamond(28, 18)
        };
    }
}
