package edu.uco.jdrumm.projectkye.Level;

import edu.uco.jdrumm.projectkye.Game.BaseObject;
import edu.uco.jdrumm.projectkye.Game.Block;
import edu.uco.jdrumm.projectkye.Game.Diamond;
import edu.uco.jdrumm.projectkye.Game.FuzzBlock;
import edu.uco.jdrumm.projectkye.Game.HorizontalMagnet;
import edu.uco.jdrumm.projectkye.Game.Kye;
import edu.uco.jdrumm.projectkye.Game.Monster;
import edu.uco.jdrumm.projectkye.Game.RoundSlider;
import edu.uco.jdrumm.projectkye.Game.Sentry;
import edu.uco.jdrumm.projectkye.Game.SquareSlider;
import edu.uco.jdrumm.projectkye.Game.VerticalMagnet;
import edu.uco.jdrumm.projectkye.Game.Wall;
import edu.uco.jdrumm.projectkye.Orientation.Direction;

public class Level4 extends Level
{

    public Level4()
    {
        super();
        setNextLevel(new Level5());
        levelMessage = "Very good, I see you are getting the hang of this";
        levelName = "Zoo";
    }

    @Override
    protected void createObjects()
    {
        objects = new BaseObject[]{
                new FuzzBlock(2, 1),
                new Wall(12, 1),
                new Wall(13, 1),
                new Monster(14, 1, Monster.Monsters.TWISTER),
                new Block(17, 1),
                new Block(22, 1),
                new Wall(24, 1),

                new Wall(2, 2, 4),
                new Wall(3, 2, 9),
                new FuzzBlock(4, 2),
                new FuzzBlock(5, 2),
                new FuzzBlock(6, 2),
                new FuzzBlock(7, 2),
                new FuzzBlock(8, 2),
                new FuzzBlock(9, 2),
                new FuzzBlock(10, 2),
                new FuzzBlock(11, 2),
                new FuzzBlock(12, 2),
                new FuzzBlock(13, 2),
                new Block(21, 2),
                new FuzzBlock(24, 2),
                new Kye(26, 2),

                new Wall(3, 3, 1),
                new Wall(4, 3, 9),
                new Monster(5, 3, Monster.Monsters.SPIKE),
                new FuzzBlock(11, 3),
                new SquareSlider(12, 3, Direction.LEFT),
                new Wall(13, 3),
                new Block(20, 3),
                new Wall(24, 3),

                new Wall(4, 4, 1),
                new Wall(5, 4),
                new Wall(6, 4),
                new Wall(7, 4),
                new Wall(8, 4),
                new Wall(9, 4),
                new Wall(10, 4),
                new Wall(11, 4),
                new Wall(12, 4),
                new Wall(13, 4),
                new Wall(14, 4),
                new Wall(15, 4),
                new Wall(16, 4),
                new Wall(17, 4),
                new Wall(18, 4),
                new Wall(19, 4),
                new Wall(20, 4),
                new Wall(21, 4),
                new Wall(22, 4),
                new Wall(23, 4),
                new Wall(24, 4),
                new Wall(25, 4),
                new Wall(26, 4),
                new Wall(27, 4),
                new Wall(28, 4),

                new Wall(5, 5),
                new SquareSlider(7, 5, Direction.RIGHT),
                new FuzzBlock(8, 5),
                new FuzzBlock(9, 5),
                new SquareSlider(12, 5, Direction.DOWN),
                new SquareSlider(13, 5, Direction.DOWN),
                new VerticalMagnet(18, 5),
                new FuzzBlock(22, 5),
                new FuzzBlock(23, 5),
                new Wall(26, 5),
                new Monster(27, 5, Monster.Monsters.GNASHER),

                new FuzzBlock(1, 6),
                new Block(2, 6),
                new FuzzBlock(3, 6),
                new Wall(4, 6, 7),
                new Wall(5, 6),
                new SquareSlider(7, 6, Direction.RIGHT),
                new SquareSlider(8, 6, Direction.UP),
                new SquareSlider(9, 6, Direction.UP),
                new FuzzBlock(10, 6),
                new SquareSlider(12, 6, Direction.DOWN),
                new SquareSlider(13, 6, Direction.DOWN),
                new SquareSlider(14, 6, Direction.LEFT),
                new SquareSlider(15, 6, Direction.LEFT),
                new FuzzBlock(18, 6),
                new Sentry(22, 6, Direction.DOWN),
                new Wall(23, 6),
                new Wall(26, 6),

                new FuzzBlock(1, 7),
                new Block(2, 7),
                new Wall(4, 7),
                new Wall(5, 7),
                new SquareSlider(8, 7, Direction.UP),
                new SquareSlider(9, 7, Direction.UP),
                new FuzzBlock(12, 7),
                new FuzzBlock(13, 7),
                new FuzzBlock(18, 7),
                new Wall(21, 7),
                new Monster(22, 7, Monster.Monsters.BLOB),
                new Wall(23, 7),
                new Wall(25, 7),
                new Wall(26, 7),
                new RoundSlider(27, 7, Direction.DOWN),
                new Wall(28, 7),

                new FuzzBlock(1, 8),
                new Block(2, 8),
                new Wall(4, 8),
                new Wall(5, 8),
                new Wall(6, 8),
                new FuzzBlock(7, 8),
                new Wall(8, 8),
                new Wall(9, 8),
                new Wall(10, 8),
                new Wall(11, 8),
                new Wall(12, 8),
                new Wall(13, 8),
                new Wall(14, 8),
                new Wall(15, 8),
                new Wall(16, 8),
                new Wall(17, 8),
                new Wall(18, 8),
                new Wall(19, 8),
                new Wall(20, 8),
                new Wall(21, 8),
                new Wall(22, 8),
                new Wall(23, 8),
                new Wall(25, 8),
                new FuzzBlock(27, 8),

                new FuzzBlock(1, 9),
                new Block(2, 9),
                new Wall(4, 9),
                new Wall(5, 9),
                new Wall(11, 9),
                new Diamond(12, 9),
                new FuzzBlock(13, 9),
                new FuzzBlock(14, 9),
                new Sentry(16, 9, Direction.RIGHT),
                new Block(17, 9),
                new Sentry(20, 9, Direction.RIGHT),
                new Wall(21, 9),
                new Wall(22, 9),
                new Wall(23, 9),
                new Wall(25, 9),
                new Wall(27, 9, 7),

                new FuzzBlock(1, 10),
                new Block(2, 10),
                new Wall(4, 10, 1),
                new Wall(5, 10),
                new Block(7, 10),
                new Block(8, 10),
                new Block(9, 10),
                new Block(10, 10),
                new Wall(11, 10),
                new Diamond(12, 10),
                new Diamond(13, 10),
                new Diamond(14, 10),
                new FuzzBlock(15, 10),
                new Wall(17, 10),
                new Wall(23, 10),
                new Wall(25, 10),
                new Wall(27, 10),

                new Wall(5, 11),
                new Block(6, 11),
                new Wall(11, 11),
                new Wall(12, 11),
                new Wall(13, 11),
                new Wall(14, 11),
                new Wall(15, 11),
                new Wall(16, 11),
                new Wall(17, 11),
                new Wall(23, 11),
                new Wall(25, 11),
                new Wall(27, 11),

                new Monster(2, 12, Monster.Monsters.BLOB),
                new Wall(5, 12),
                new Block(7, 12),
                new Monster(12, 12, Monster.Monsters.SNAKE),
                new FuzzBlock(13, 12),
                new Wall(23, 12),
                new Wall(25, 12),
                new Wall(27, 12),

                new Wall(5, 13),
                new Block(6, 13),
                new Block(7, 13),
                new Block(8, 13),
                new Block(9, 13),
                new Block(10, 13),
                new Block(11, 13),
                new Block(12, 13),
                new Wall(13, 13),
                new Wall(14, 13),
                new Wall(15, 13),
                new Wall(16, 13, 6),
                new Wall(20, 13, 4),
                new Wall(21, 13),
                new Wall(22, 13),
                new Wall(23, 13),
                new Wall(25, 13),
                new Wall(27, 13),

                new Wall(1, 14),
                new Wall(2, 14),
                new Wall(3, 14),
                new FuzzBlock(4, 14),
                new Wall(5, 14),
                new Wall(14, 14),
                new HorizontalMagnet(15, 14),
                new VerticalMagnet(22, 14),
                new Wall(23, 14),
                new FuzzBlock(26, 14),
                new Wall(27, 14),

                new Wall(5, 15),
                new Wall(6, 15),
                new Wall(7, 15),
                new Wall(8, 15),
                new Wall(9, 15),
                new Wall(10, 15),
                new Wall(11, 15),
                new Wall(12, 15),
                new Wall(13, 15),
                new Wall(14, 15),
                new Wall(15, 15),
                new Wall(16, 15),
                new Wall(17, 15),
                new Wall(18, 15),
                new Wall(19, 15),
                new Wall(20, 15),
                new Wall(21, 15),
                new Wall(22, 15),
                new Wall(23, 15),
                new Wall(26, 15),
                new Wall(27, 15),

                new FuzzBlock(3, 16),
                new FuzzBlock(4, 16),
                new FuzzBlock(5, 16),
                new FuzzBlock(6, 16),
                new RoundSlider(16, 16, Direction.DOWN),
                new RoundSlider(17, 16, Direction.DOWN),
                new RoundSlider(18, 16, Direction.DOWN),
                new Wall(22, 16),
                new FuzzBlock(26, 16),
                new Wall(27, 16),

                new Wall(1, 17),
                new Wall(2, 17, 9),
                new RoundSlider(3, 17, Direction.LEFT),
                new RoundSlider(4, 17, Direction.LEFT),
                new RoundSlider(5, 17, Direction.LEFT),
                new RoundSlider(15, 17, Direction.DOWN),
                new RoundSlider(16, 17, Direction.DOWN),
                new RoundSlider(17, 17, Direction.DOWN),
                new RoundSlider(18, 17, Direction.DOWN),
                new RoundSlider(19, 17, Direction.DOWN),
                new Wall(22, 17),
                new Wall(23, 17),
                new Wall(24, 17),
                new Wall(25, 17),
                new Wall(26, 17),
                new Wall(27, 17),

                new Monster(2, 18, Monster.Monsters.SNAKE),
                new FuzzBlock(4, 18),
                new FuzzBlock(5, 18),
                new FuzzBlock(6, 18),
                new FuzzBlock(14, 18),
                new FuzzBlock(15, 18),
                new FuzzBlock(16, 18),
                new FuzzBlock(17, 18),
                new FuzzBlock(18, 18),
                new RoundSlider(19, 18, Direction.DOWN),
                new RoundSlider(20, 18, Direction.DOWN),
                new FuzzBlock(22, 18)

        };
    }
}
