package edu.uco.jdrumm.projectkye.Level;

import edu.uco.jdrumm.projectkye.Game.BaseObject;
import edu.uco.jdrumm.projectkye.Game.Block;
import edu.uco.jdrumm.projectkye.Game.Diamond;
import edu.uco.jdrumm.projectkye.Game.FuzzBlock;
import edu.uco.jdrumm.projectkye.Game.Kye;
import edu.uco.jdrumm.projectkye.Game.RoundSlider;
import edu.uco.jdrumm.projectkye.Game.VerticalMagnet;
import edu.uco.jdrumm.projectkye.Game.Wall;
import edu.uco.jdrumm.projectkye.Orientation.Direction;

public class Level2 extends Level {

    public Level2()
    {
        super();
        setNextLevel(new Level3());
    }


    @Override
    public void createObjects()
    {
        objects = new BaseObject[] {
                new Kye(28, 1),
                new Diamond(1, 1),
                new RoundSlider(2, 1, Direction.RIGHT),
                new RoundSlider(3, 1, Direction.RIGHT),
                new RoundSlider(4, 1, Direction.RIGHT),
                new RoundSlider(5, 1, Direction.RIGHT),
                new RoundSlider(1, 2, Direction.RIGHT),
                new RoundSlider(2, 2, Direction.RIGHT),
                new RoundSlider(3, 2, Direction.RIGHT),
                new RoundSlider(4, 2, Direction.RIGHT),
                new RoundSlider(5, 2, Direction.RIGHT),
                new FuzzBlock(6, 1),
                new FuzzBlock(6, 2),
                new Wall(1, 3),
                new Wall(2, 3),
                new Wall(3, 3),
                new Wall(4, 3),
                new Wall(5, 3),
                new Wall(6, 3, 9),
                new Wall(6, 4),
                new Wall(6, 5),
                new Wall(6, 6, 1),
                new Wall(7, 7, 1),
                new Wall(8, 8, 1),
                new Wall(9, 9, 1),
                new Wall(10, 10, 1),
                new Wall(11, 11, 1),
                new Wall(12, 12, 1),
                new Wall(13, 12),
                new Wall(14, 12),
                new Wall(15, 12),
                new Wall(16, 12),
                new Wall(17, 12),
                new Wall(18, 12),
                new Wall(19, 12),
                new Wall(20, 12),
                new Wall(21, 12),
                new Wall(22, 12),
                new Wall(23, 12),
                new Wall(24, 12),
                new Wall(24, 11),
                new Wall(24, 10),
                new Wall(24, 9),
                new Wall(24, 8),
                new Wall(24, 7),
                new Wall(24, 6),
                new Wall(24, 5),
                new Wall(24, 4, 9),
                new Wall(23, 4, 7),
                new Wall(21, 11),
                new Wall(21, 10),
                new Wall(21, 9),
                new Wall(21, 8),
                new Wall(21, 7),
                new Wall(21, 6),
                new Wall(21, 5),
                new Wall(21, 4),
                new Wall(20, 9),
                new Wall(20, 8),
                new Wall(20, 7),
                new Wall(20, 6),
                new Wall(20, 5),
                new Wall(20, 4),
                new Wall(20, 3),
                new Wall(20, 2),
                new Wall(19, 3, 7),
                new Wall(18, 4, 7),
                new Wall(17, 5, 7),
                new Wall(16, 6, 4),
                new Wall(17, 7, 1),
                new Wall(18, 8, 1),
                new Wall(19, 9, 1),
                new Wall(19, 4),
                new Wall(18, 5),
                new Wall(17, 6),
                new Wall(18, 7),
                new Wall(19, 8),
                new Wall(10, 9),
                new Wall(10, 8),
                new Wall(10, 7),
                new Wall(10, 6),
                new Wall(10, 5),
                new Wall(10, 4),
                new Wall(10, 3),
                new Wall(10, 2),
                new Wall(11, 3, 9),
                new Wall(12, 4, 9),
                new Wall(13, 5, 9),
                new Wall(14, 6, 6),
                new Wall(13, 7, 3),
                new Wall(12, 8, 3),
                new Wall(11, 9, 3),
                new Wall(11, 4),
                new Wall(12, 5),
                new Wall(13, 6),
                new Wall(12, 7),
                new Wall(11, 8),
                new FuzzBlock(10, 1),
                new FuzzBlock(20, 1),
                new FuzzBlock(15, 6),
                new RoundSlider(14, 7, Direction.UP),
                new RoundSlider(15, 7, Direction.UP),
                new RoundSlider(16, 7, Direction.UP),
                new RoundSlider(13, 8, Direction.UP),
                new RoundSlider(14, 8, Direction.UP),
                new RoundSlider(15, 8, Direction.UP),
                new RoundSlider(16, 8, Direction.UP),
                new RoundSlider(17, 8, Direction.UP),
                new RoundSlider(12, 9, Direction.UP),
                new RoundSlider(13, 9, Direction.UP),
                new RoundSlider(14, 9, Direction.UP),
                new RoundSlider(15, 9, Direction.UP),
                new RoundSlider(16, 9, Direction.UP),
                new RoundSlider(17, 9, Direction.UP),
                new RoundSlider(18, 9, Direction.UP),
                new VerticalMagnet(22, 11),
                new Wall(24, 13),
                new Wall(24, 14),
                new Wall(24, 15),
                new Wall(24, 16),
                new Wall(24, 17),
                new FuzzBlock(24, 18),
                new FuzzBlock(25, 18),
                new FuzzBlock(26, 18),
                new FuzzBlock(27, 18),
                new FuzzBlock(28, 17),
                new Diamond(28, 18),
                new Wall(26, 17, 4),
                new Wall(27, 17),
                new Wall(27, 16, 7),
                new Wall(28, 16),
                new Wall(28, 15, 7),
                new RoundSlider(25, 17, Direction.DOWN),
                new RoundSlider(25, 16, Direction.DOWN),
                new RoundSlider(26, 16, Direction.DOWN),
                new Wall(23, 16),
                new Wall(22, 16),
                new Wall(21, 16),
                new Wall(20, 16),
                new Wall(19, 16),
                new Wall(18, 16),
                new Wall(17, 16),
                new Wall(16, 16),
                new Wall(15, 16),
                new Wall(14, 15, 9),
                new Wall(14, 13, 3),
                new FuzzBlock(13, 15),
                new Block(13, 14),
                new RoundSlider(14, 14, Direction.LEFT),
                new RoundSlider(15, 13, Direction.LEFT),
                new RoundSlider(15, 14, Direction.LEFT),
                new RoundSlider(15, 15, Direction.LEFT),
                new RoundSlider(16, 13, Direction.LEFT),
                new RoundSlider(16, 14, Direction.LEFT),
                new RoundSlider(16, 15, Direction.LEFT),
                new RoundSlider(17, 13, Direction.LEFT),
                new RoundSlider(17, 14, Direction.LEFT),
                new RoundSlider(17, 15, Direction.LEFT),
                new RoundSlider(18, 13, Direction.LEFT),
                new RoundSlider(18, 14, Direction.LEFT),
                new RoundSlider(18, 15, Direction.LEFT),
                new RoundSlider(19, 13, Direction.LEFT),
                new RoundSlider(19, 14, Direction.LEFT),
                new RoundSlider(19, 15, Direction.LEFT),
                new RoundSlider(20, 13, Direction.LEFT),
                new RoundSlider(20, 14, Direction.LEFT),
                new RoundSlider(20, 15, Direction.LEFT),
                new Diamond(23, 13),
                new Diamond(23, 15),
                new Wall(12, 15, 9),
                new Wall(11, 14, 9),
                new Wall(10, 13, 9),
                new Wall(9, 12, 9),
                new Wall(8, 11, 9),
                new Wall(7, 10, 9),
                new Wall(6, 9, 9),
                new Wall(5, 8, 9),
                new Wall(11, 15),
                new Wall(10, 14),
                new Wall(9, 13),
                new Wall(8, 12),
                new Wall(7, 11),
                new Wall(6, 10),
                new Wall(10, 15),
                new Wall(9, 14),
                new Wall(8, 13),
                new Wall(7, 12),
                new Wall(6, 11),
                new Wall(5, 11, 7),
                new Wall(4, 12, 7),
                new Wall(3, 13, 4),
                new Wall(4, 14, 1),
                new Wall(5, 15, 1),
                new Wall(5, 12),
                new Wall(4, 13),
                new Wall(5, 14),
                new Wall(6, 15),
                new Wall(6, 12),
                new Wall(4, 8),
                new Wall(3, 8),
                new Wall(2, 8),
                new Diamond(1, 7),
                new FuzzBlock(1, 8),
                new Diamond(1, 9),
                new RoundSlider(2, 9, Direction.DOWN),
                new RoundSlider(3, 9, Direction.DOWN),
                new RoundSlider(3, 9, Direction.DOWN),
                new RoundSlider(1, 10, Direction.DOWN),
                new RoundSlider(2, 10, Direction.DOWN),
                new RoundSlider(3, 10, Direction.DOWN),
                new RoundSlider(4, 10, Direction.DOWN),
                new RoundSlider(5, 10, Direction.DOWN),
                new RoundSlider(1, 11, Direction.DOWN),
                new RoundSlider(2, 11, Direction.DOWN),
                new RoundSlider(3, 11, Direction.DOWN),
                new RoundSlider(4, 11, Direction.DOWN),
                new RoundSlider(1, 12, Direction.DOWN),
                new RoundSlider(2, 12, Direction.DOWN),
                new RoundSlider(3, 12, Direction.DOWN),
                new RoundSlider(1, 13, Direction.DOWN),
                new RoundSlider(2, 13, Direction.DOWN),
                new FuzzBlock(1, 14),
                new FuzzBlock(2, 14),
                new FuzzBlock(3, 14),
                new FuzzBlock(6, 16),
                new FuzzBlock(6, 17),
                new FuzzBlock(6, 18),
                new FuzzBlock(7, 15),
                new FuzzBlock(8, 15),
                new FuzzBlock(9, 15),
                new FuzzBlock(9, 16),
                new FuzzBlock(9, 17),
                new FuzzBlock(9, 18),
                new FuzzBlock(9, 19),
                new Diamond(7, 18),
                new RoundSlider(7, 17, Direction.UP),
                new RoundSlider(7, 16, Direction.UP),
                new RoundSlider(8, 16, Direction.UP),
                new RoundSlider(8, 17, Direction.UP),
                new RoundSlider(8, 18, Direction.UP),
                new Diamond(20, 11)
        };
    }
}
