package edu.uco.jdrumm.projectkye.Level;

import edu.uco.jdrumm.projectkye.Game.BaseObject;
import edu.uco.jdrumm.projectkye.Game.BlockCircle;
import edu.uco.jdrumm.projectkye.Game.Diamond;
import edu.uco.jdrumm.projectkye.Game.FuzzBlock;
import edu.uco.jdrumm.projectkye.Game.Kye;
import edu.uco.jdrumm.projectkye.Game.Monster;
import edu.uco.jdrumm.projectkye.Game.Rotator;
import edu.uco.jdrumm.projectkye.Game.RoundSlider;
import edu.uco.jdrumm.projectkye.Game.VerticalMagnet;
import edu.uco.jdrumm.projectkye.Game.Wall;
import edu.uco.jdrumm.projectkye.Orientation.Direction;
import edu.uco.jdrumm.projectkye.Orientation.Rotation;

public class Level12 extends Level
{
    public Level12()
    {
        super();
        setNextLevel(new Level13());
        levelMessage = "Piece of cake!";
        levelName = "Getout";
    }

    @Override
    protected void createObjects()
    {
        objects = new BaseObject[]{
                new BlockCircle(24, 1),
                new Monster(26, 1, Monster.Monsters.GNASHER),
                new BlockCircle(27, 1),

                new FuzzBlock(4, 2),
                new BlockCircle(24, 2),

                new Wall(3, 3, 6),
                new RoundSlider(4, 3, Direction.UP),
                new Wall(5, 3, 4),
                new Rotator(6, 3, Rotation.CLOCKWISE),
                new BlockCircle(24, 3),

                new Wall(1, 4),
                new Wall(2, 4, 3),
                new RoundSlider(3, 4, Direction.UP),
                new RoundSlider(4, 4, Direction.UP),
                new RoundSlider(5, 4, Direction.UP),
                new Wall(6, 4, 1),
                new BlockCircle(24, 4),
                new Diamond(28, 4),

                new Wall(1, 5, 3),
                new RoundSlider(2, 5, Direction.UP),
                new RoundSlider(3, 5, Direction.UP),
                new RoundSlider(4, 5, Direction.UP),
                new RoundSlider(5, 5, Direction.UP),
                new RoundSlider(6, 5, Direction.UP),
                new Wall(7, 5, 1),
                new Wall(8, 5),
                new Wall(9, 5),
                new Wall(10, 5),
                new Wall(11, 5),
                new Wall(12, 5),
                new Wall(13, 5),
                new Wall(14, 5),
                new Wall(15, 5),
                new Wall(16, 5),
                new Wall(17, 5),
                new Wall(18, 5),
                new Wall(19, 5),
                new Wall(20, 5, 6),
                new Wall(23, 5, 4),
                new Wall(24, 5),
                new Wall(25, 5),
                new Wall(26, 5),
                new Wall(27, 5),
                new Wall(28, 5),

                new RoundSlider(1, 6, Direction.UP),
                new RoundSlider(2, 6, Direction.UP),
                new RoundSlider(3, 6, Direction.UP),
                new RoundSlider(4, 6, Direction.UP),
                new RoundSlider(5, 6, Direction.UP),
                new RoundSlider(6, 6, Direction.UP),
                new RoundSlider(7, 6, Direction.UP),
                new Wall(8, 6, 1),
                new VerticalMagnet(12, 6),
                new Wall(15, 6),
                new RoundSlider(16, 6, Direction.RIGHT),
                new RoundSlider(17, 6, Direction.RIGHT),
                new RoundSlider(18, 6, Direction.RIGHT),
                new RoundSlider(19, 6, Direction.RIGHT),
                new Wall(20, 6),
                new FuzzBlock(25, 6),
                new FuzzBlock(26, 6),
                new Monster(27, 6, Monster.Monsters.TWISTER),

                new RoundSlider(1, 7, Direction.UP),
                new RoundSlider(2, 7, Direction.UP),
                new RoundSlider(3, 7, Direction.UP),
                new RoundSlider(4, 7, Direction.UP),
                new Diamond(5, 7),
                new RoundSlider(6, 7, Direction.UP),
                new RoundSlider(7, 7, Direction.UP),
                new RoundSlider(8, 7, Direction.UP),
                new Wall(9, 7),
                new Wall(15, 7),
                new RoundSlider(16, 7, Direction.RIGHT),
                new RoundSlider(17, 7, Direction.RIGHT),
                new RoundSlider(18, 7, Direction.RIGHT),
                new RoundSlider(19, 7, Direction.RIGHT),
                new Wall(20, 7),
                new FuzzBlock(25, 7),
                new Diamond(26, 7),

                new Wall(1, 8),
                new Wall(2, 8),
                new Wall(3, 8),
                new Wall(4, 8),
                new Wall(5, 8),
                new Wall(6, 8),
                new Wall(7, 8),
                new Wall(8, 8),
                new Wall(9, 8),
                new Wall(10, 8),
                new Wall(11, 8, 6),
                new Wall(15, 8),
                new RoundSlider(16, 8, Direction.RIGHT),
                new RoundSlider(17, 8, Direction.RIGHT),
                new RoundSlider(18, 8, Direction.RIGHT),
                new RoundSlider(19, 8, Direction.RIGHT),
                new FuzzBlock(20, 8),
                new Rotator(25, 8, Rotation.CLOCKWISE),
                new FuzzBlock(26, 8),

                new Wall(2, 9, 2),
                new Rotator(9, 9, Rotation.COUNTER_CLOCKWISE),
                new Rotator(10, 9, Rotation.COUNTER_CLOCKWISE),
                new Rotator(11, 9, Rotation.COUNTER_CLOCKWISE),
                new Wall(15, 9),
                new RoundSlider(16, 9, Direction.RIGHT),
                new RoundSlider(17, 9, Direction.RIGHT),
                new RoundSlider(18, 9, Direction.RIGHT),
                new Wall(19, 9, 7),
                new Wall(20, 9, 9),
                new Wall(23, 9, 8),
                new Wall(25, 9, 7),
                new Wall(26, 9, 9),
                new Wall(28, 9, 7),

                new Rotator(1, 10, Rotation.COUNTER_CLOCKWISE),
                new Wall(15, 10),
                new Wall(16, 10),
                new Wall(17, 10),
                new Wall(18, 10),
                new Wall(19, 10),
                new Wall(20, 10, 3),
                new Wall(23, 10),
                new Wall(25, 10),
                new Wall(26, 10),
                new Wall(28, 10),

                new Diamond(3, 11),
                new Rotator(4, 11, Rotation.CLOCKWISE),
                new Wall(5, 11, 8),
                new Wall(15, 11),
                new Wall(23, 11),
                new Wall(25, 11),
                new Wall(26, 11),
                new Wall(28, 11),

                new RoundSlider(1, 12, Direction.RIGHT),
                new RoundSlider(2, 12, Direction.RIGHT),
                new Diamond(3, 12),
                new Rotator(4, 12, Rotation.CLOCKWISE),
                new Wall(5, 12),
                new Wall(15, 12),
                new Wall(23, 12),
                new Wall(25, 12),
                new Wall(26, 12),
                new Wall(28, 12),

                new RoundSlider(1, 13, Direction.RIGHT),
                new Diamond(2, 13),
                new Diamond(3, 13),
                new Rotator(4, 13, Rotation.CLOCKWISE),
                new Wall(5, 13),
                new Kye(7, 13),
                new Wall(13, 13, 8),
                new Wall(15, 13),
                new Wall(23, 13),
                new Wall(25, 13),
                new Wall(26, 13),
                new Wall(28, 13),

                new RoundSlider(1, 14, Direction.RIGHT),
                new Diamond(2, 14),
                new Wall(3, 14, 4),
                new Wall(4, 14),
                new Wall(5, 14, 3),
                new Wall(13, 14),
                new Wall(15, 14),
                new Wall(23, 14),
                new Wall(25, 14),
                new Wall(26, 14),
                new Wall(28, 14),

                new RoundSlider(1, 15, Direction.RIGHT),
                new Diamond(2, 15),
                new Rotator(3, 15, Rotation.CLOCKWISE),
                new Wall(4, 15),
                new Wall(13, 15),
                new Wall(15, 15, 2),
                new Wall(23, 15),
                new Wall(25, 15),
                new Wall(26, 15),
                new Wall(28, 15),

                new RoundSlider(1, 16, Direction.RIGHT),
                new Diamond(2, 16),
                new Rotator(3, 16, Rotation.CLOCKWISE),
                new Wall(4, 16),
                new Wall(5, 16),
                new Wall(6, 16),
                new Wall(7, 16),
                new Wall(8, 16),
                new Wall(9, 16, 6),
                new Wall(13, 16),
                new Wall(23, 16),
                new Wall(25, 16, 1),
                new Wall(26, 16, 3),
                new Wall(28, 16, 1),

                new RoundSlider(1, 17, Direction.RIGHT),
                new Diamond(2, 17),
                new Rotator(3, 17, Rotation.COUNTER_CLOCKWISE),
                new Wall(13, 17),
                new Wall(15, 17, 8),
                new Wall(23, 17),
                new Rotator(28, 17, Rotation.COUNTER_CLOCKWISE),

                new Rotator(1, 18, Rotation.COUNTER_CLOCKWISE),
                new Rotator(2, 18, Rotation.COUNTER_CLOCKWISE),
                new Rotator(3, 18, Rotation.COUNTER_CLOCKWISE),
                new Wall(4, 18, 7),
                new Wall(5, 18),
                new Wall(6, 18),
                new Wall(7, 18),
                new Wall(8, 18),
                new Wall(9, 18),
                new Wall(10, 18),
                new Wall(11, 18),
                new Wall(12, 18),
                new Wall(13, 18),
                new Wall(14, 18),
                new Wall(15, 18),

                new Wall(23, 18),
                new Rotator(24, 18, Rotation.COUNTER_CLOCKWISE),
                new Rotator(25, 18, Rotation.COUNTER_CLOCKWISE),
                new Rotator(28, 18, Rotation.COUNTER_CLOCKWISE)
        };
    }
}
