package edu.uco.jdrumm.projectkye.Level;

import edu.uco.jdrumm.projectkye.Game.BaseObject;
import edu.uco.jdrumm.projectkye.Game.BlackHole;
import edu.uco.jdrumm.projectkye.Game.Diamond;
import edu.uco.jdrumm.projectkye.Game.ForceField;
import edu.uco.jdrumm.projectkye.Game.FuzzBlock;
import edu.uco.jdrumm.projectkye.Game.Kye;
import edu.uco.jdrumm.projectkye.Game.Monster;
import edu.uco.jdrumm.projectkye.Game.RoundSlider;
import edu.uco.jdrumm.projectkye.Game.SquareSlider;
import edu.uco.jdrumm.projectkye.Game.TimeBlock;
import edu.uco.jdrumm.projectkye.Game.Wall;
import edu.uco.jdrumm.projectkye.Orientation.Direction;

public class Level13 extends Level
{
    public Level13()
    {
        super();
        setNextLevel(new Level14());
        levelMessage = "Should you be working?";
        levelName = "Fallin";
    }

    @Override
    protected void createObjects()
    {
        objects = new BaseObject[]{
                new ForceField(7, 1, Direction.LEFT),
                new Wall(10, 1),
                new Diamond(11, 1),
                new FuzzBlock(12, 1),
                new Wall(13, 1),
                new RoundSlider(14, 1, Direction.RIGHT),
                new FuzzBlock(15, 1),
                new FuzzBlock(18, 1),
                new RoundSlider(20, 1, Direction.RIGHT),
                new FuzzBlock(21, 1),
                new FuzzBlock(24, 1),
                new RoundSlider(26, 1, Direction.RIGHT),
                new FuzzBlock(27, 1),
                new Diamond(28, 1),

                new Wall(1, 2),
                new Wall(2, 2),
                new Wall(3, 2),
                new ForceField(4, 2, Direction.UP),
                new Wall(5, 2),
                new Wall(7, 2, 8),
                new Wall(10, 2),
                new FuzzBlock(11, 2),
                new RoundSlider(12, 2, Direction.DOWN),
                new Wall(13, 2),
                new FuzzBlock(15, 2),
                new RoundSlider(18, 2, Direction.RIGHT),
                new FuzzBlock(19, 2),
                new FuzzBlock(21, 2),
                new RoundSlider(23, 2, Direction.RIGHT),
                new FuzzBlock(24, 2),
                new FuzzBlock(27, 2),
                new Diamond(28, 2),

                new Wall(3, 3),
                new Wall(5, 3),
                new Wall(7, 3),
                new Wall(10, 3, 1),
                new Wall(11, 3, 9),
                new FuzzBlock(12, 3),
                new Wall(13, 3),
                new Wall(15, 3),
                new Wall(16, 3),
                new Wall(17, 3),
                new Wall(18, 3),
                new Wall(19, 3),
                new Wall(20, 3),
                new Wall(21, 3),
                new Wall(22, 3),
                new Wall(23, 3),
                new Wall(24, 3),
                new Wall(25, 3),
                new Wall(26, 3),
                new Wall(27, 3),
                new Wall(28, 3),

                new Monster(2, 4, Monster.Monsters.BLOB),
                new Wall(3, 4),
                new Wall(5, 4),
                new BlackHole(7, 4),
                new Monster(8, 4, Monster.Monsters.TWISTER),
                new Diamond(10, 4),
                new Wall(11, 4),
                new Wall(13, 4),
                new Kye(28, 4),

                new Wall(2, 5),
                new Wall(3, 5),
                new ForceField(4, 5, Direction.DOWN),
                new Wall(5, 5),
                new Wall(7, 5, 1),
                new Wall(8, 5),
                new Wall(9, 5),
                new Wall(10, 5),
                new Wall(11, 5, 3),
                new Wall(13, 5),

                new Wall(2, 6),
                new ForceField(5, 6, Direction.LEFT),
                new ForceField(7, 6, Direction.LEFT),
                new Wall(13, 6),
                new RoundSlider(21, 6, Direction.DOWN),
                new RoundSlider(22, 6, Direction.DOWN),
                new RoundSlider(23, 6, Direction.DOWN),

                new ForceField(1, 7, Direction.DOWN),
                new Wall(2, 7),
                new Wall(5, 7, 7),
                new ForceField(6, 7, Direction.UP),
                new Wall(7, 7, 9),
                new ForceField(13, 7, Direction.LEFT),
                new RoundSlider(20, 7, Direction.DOWN),
                new SquareSlider(21, 7, Direction.DOWN),
                new SquareSlider(22, 7, Direction.DOWN),
                new SquareSlider(23, 7, Direction.DOWN),
                new RoundSlider(24, 7, Direction.DOWN),

                new Wall(2, 8),
                new Wall(4, 8, 7),
                new Wall(5, 8),
                new Wall(7, 8),
                new Wall(8, 8),
                new Wall(9, 8),
                new Wall(10, 8),
                new ForceField(11, 8, Direction.DOWN),
                new Wall(12, 8),
                new Wall(13, 8),
                new Wall(14, 8),
                new SquareSlider(20, 8, Direction.DOWN),
                new TimeBlock(21, 8, 3),
                new TimeBlock(22, 8, 3),
                new TimeBlock(23, 8, 3),
                new SquareSlider(24, 8, Direction.DOWN),

                new Wall(4, 9),
                new Wall(10, 9),
                new Wall(12, 9),
                new Diamond(13, 9),
                new Wall(14, 9),
                new RoundSlider(18, 9, Direction.RIGHT),
                new SquareSlider(19, 9, Direction.RIGHT),
                new Diamond(20, 9),
                new Diamond(21, 9),
                new Diamond(22, 9),
                new Diamond(23, 9),
                new Diamond(24, 9),
                new SquareSlider(25, 9, Direction.LEFT),
                new RoundSlider(26, 9, Direction.LEFT),

                new Wall(1, 10, 9),
                new ForceField(2, 10, Direction.DOWN),
                new Wall(3, 10),
                new Wall(5, 10),
                new Wall(6, 10),
                new Wall(5, 10),
                new Wall(8, 10, 6),
                new Wall(10, 10),
                new Wall(12, 10),
                new Wall(14, 10),
                new Wall(15, 10),
                new RoundSlider(17, 10, Direction.RIGHT),
                new SquareSlider(18, 10, Direction.RIGHT),
                new TimeBlock(19, 10, 3),
                new Diamond(20, 10),
                new Diamond(21, 10),
                new Diamond(22, 10),
                new Diamond(23, 10),
                new Diamond(24, 10),
                new TimeBlock(25, 10, 3),
                new SquareSlider(26, 10, Direction.LEFT),
                new RoundSlider(27, 10, Direction.LEFT),

                new Wall(1, 11, 3),
                new Wall(3, 11),
                new Wall(5, 11),
                new Wall(10, 11),
                new Wall(12, 11),
                new Wall(15, 11),
                new RoundSlider(17, 11, Direction.RIGHT),
                new SquareSlider(18, 11, Direction.RIGHT),
                new TimeBlock(19, 11, 3),
                new Diamond(20, 11),
                new Diamond(21, 11),
                new Diamond(22, 11),
                new Diamond(23, 11),
                new Diamond(24, 11),
                new TimeBlock(25, 11, 3),
                new SquareSlider(26, 11, Direction.LEFT),
                new RoundSlider(27, 11, Direction.LEFT),

                new Wall(3, 12),
                new Wall(5, 12),
                new Wall(7, 12),
                new Wall(8, 12),
                new Wall(9, 12),
                new Wall(10, 12),
                new Wall(12, 12, 1),
                new Wall(13, 12, 6),
                new Wall(15, 12),
                new RoundSlider(17, 12, Direction.RIGHT),
                new SquareSlider(18, 12, Direction.RIGHT),
                new TimeBlock(19, 12, 3),
                new Diamond(20, 12),
                new Diamond(21, 12),
                new Diamond(22, 12),
                new Diamond(23, 12),
                new Diamond(24, 12),
                new TimeBlock(25, 12, 3),
                new SquareSlider(26, 12, Direction.LEFT),
                new RoundSlider(27, 12, Direction.LEFT),

                new Wall(1, 13, 9),
                new Wall(3, 13),
                new Wall(5, 13),
                new Wall(7, 13),
                new Wall(15, 13),
                new RoundSlider(18, 13, Direction.RIGHT),
                new SquareSlider(19, 13, Direction.RIGHT),
                new Diamond(20, 13),
                new Diamond(21, 13),
                new Diamond(22, 13),
                new Diamond(23, 13),
                new Diamond(24, 13),
                new SquareSlider(25, 13, Direction.LEFT),
                new RoundSlider(26, 13, Direction.LEFT),

                new Wall(1, 14),
                new Wall(3, 14),
                new Wall(7, 14),
                new Diamond(8, 14),
                new Wall(9, 14),
                new Wall(10, 14),
                new Wall(11, 14),
                new Wall(12, 14),
                new Wall(13, 14),
                new Wall(15, 14),

                new Wall(1, 15),
                new Wall(4, 15),
                new Wall(5, 15),
                new ForceField(6, 15, Direction.DOWN),
                new Wall(7, 15),
                new Wall(8, 15),
                new Wall(9, 15),
                new Wall(10, 15),
                new Wall(11, 15),
                new Wall(13, 15),
                new Wall(15, 15),
                new TimeBlock(20, 15, 3),
                new TimeBlock(21, 15, 3),
                new TimeBlock(22, 15, 3),
                new TimeBlock(23, 15, 3),
                new TimeBlock(24, 15, 3),

                new Wall(1, 16),
                new Wall(13, 16),
                new ForceField(15, 16, Direction.LEFT),
                new SquareSlider(20, 16, Direction.UP),
                new SquareSlider(21, 16, Direction.UP),
                new SquareSlider(22, 16, Direction.UP),
                new SquareSlider(23, 16, Direction.UP),
                new SquareSlider(24, 16, Direction.UP),
                new Wall(26, 16, 7),
                new Wall(27, 16),
                new Wall(28, 16),

                new Wall(1, 17, 3),
                new ForceField(2, 17, Direction.DOWN),
                new Wall(3, 17),
                new Wall(4, 17),
                new Wall(5, 17),
                new Wall(6, 17),
                new Wall(7, 17),
                new Wall(8, 17),
                new Wall(9, 17),
                new ForceField(10, 17, Direction.UP),
                new Wall(11, 17),
                new Wall(12, 17),
                new Wall(14, 17),
                new Wall(15, 17),
                new RoundSlider(20, 17, Direction.UP),
                new RoundSlider(21, 17, Direction.UP),
                new RoundSlider(22, 17, Direction.UP),
                new RoundSlider(23, 17, Direction.UP),
                new RoundSlider(24, 17, Direction.UP),
                new Wall(26, 17),
                new FuzzBlock(27, 17),
                new FuzzBlock(28, 17),

                new ForceField(14, 18, Direction.RIGHT),
                new FuzzBlock(26, 18),
                new Diamond(27, 18),
                new RoundSlider(28, 18, Direction.LEFT)
        };
    }
}
